service: aws-sls-employee-api
frameworkVersion: '2 || 3'

custom:
  tableName: 'CustomAppEmployees'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ EmployeeTable, Arn ]
  environment:
    TABLENAME: ${self:custom.tableName}
    NODE_ENV: 'production'
    REGION: 'ap-south-1'

functions:
  employee-api:
    handler: handler.handler
    layers:
      - arn:aws:lambda:ap-south-1:101066323403:layer:Express-Dyanmo-SDK:1
    events:
      - httpApi: '*'

resources:
  Resources:
    EmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: LocationId
            AttributeType: S
          - AttributeName: EmployeeCode
            AttributeType: S
        KeySchema:
          - AttributeName: LocationId
            KeyType: HASH
          - AttributeName: EmployeeCode
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
